# Generated by Django 5.2.6 on 2025-09-08 05:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('line', models.CharField(max_length=50)),
                ('zone', models.CharField(choices=[('western', 'Western'), ('central', 'Central'), ('eastern', 'Eastern'), ('southern', 'Southern')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ml_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metro_reviews.station')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('rating_1_count', models.PositiveIntegerField(default=0)),
                ('rating_2_count', models.PositiveIntegerField(default=0)),
                ('rating_3_count', models.PositiveIntegerField(default=0)),
                ('rating_4_count', models.PositiveIntegerField(default=0)),
                ('rating_5_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metro_reviews.station')),
            ],
        ),
        migrations.CreateModel(
            name='AspectSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(choices=[('cleanliness', 'Cleanliness'), ('safety', 'Safety'), ('punctuality', 'Punctuality'), ('crowd_management', 'Crowd Management'), ('staff_behavior', 'Staff Behavior'), ('accessibility', 'Accessibility'), ('facilities', 'Facilities'), ('connectivity', 'Connectivity')], max_length=30)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10)),
                ('score', models.DecimalField(decimal_places=3, max_digits=4)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='metro_reviews.review')),
            ],
            options={
                'unique_together': {('review', 'aspect')},
            },
        ),
        migrations.CreateModel(
            name='AspectStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(max_length=30)),
                ('positive_count', models.PositiveIntegerField(default=0)),
                ('negative_count', models.PositiveIntegerField(default=0)),
                ('neutral_count', models.PositiveIntegerField(default=0)),
                ('satisfaction_percentage', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metro_reviews.station')),
            ],
            options={
                'unique_together': {('station', 'aspect')},
            },
        ),
    ]
