# Generated by Django 5.2.6 on 2025-09-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='zone',
        ),
        migrations.AlterField(
            model_name='aspectsentiment',
            name='aspect',
            field=models.CharField(choices=[('metro_station_infrastructure', 'Metro Station Infrastructure'), ('metro_station_connectivity', 'Metro Station Connectivity'), ('general_safety', 'General Safety'), ('crowd_management', 'Crowd Management'), ('metro_frequency', 'Metro Frequency'), ('cleanliness', 'Cleanliness'), ('womens_safety', "Women's Safety"), ('ticketing_system', 'Ticketing System'), ('staff_behavior', 'Staff Behavior')], max_length=30),
        ),
    ]
