# Generated by Django 5.2.6 on 2025-09-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro_reviews', '0002_remove_station_zone_alter_aspectsentiment_aspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspectstats',
            name='aspect',
            field=models.CharField(max_length=35),
        ),
    ]
